TRUNCATE TABLE retrosp_row_field;
TRUNCATE TABLE retrosp_step_parameter;
TRUNCATE TABLE retrosp_step;
TRUNCATE TABLE prosp_hop_field;
TRUNCATE TABLE prosp_hop;
TRUNCATE TABLE prosp_workflow_note;
TRUNCATE TABLE prosp_step_parameter;
ALTER TABLE retrosp_workflow CHANGE id_root id_root INT( 11 ) NULL;
UPDATE retrosp_workflow SET id_root = NULL, id_parent = NULL;
TRUNCATE TABLE retrosp_workflow;
ALTER TABLE retrosp_workflow CHANGE id_root id_root INT( 11 ) NOT NULL;
TRUNCATE TABLE retrosp_workflow;
TRUNCATE TABLE prosp_step;
TRUNCATE TABLE prosp_note;
ALTER TABLE prosp_workflow CHANGE id_root id_root INT( 11 ) NULL;
UPDATE prosp_workflow SET id_root = NULL, id_parent = NULL;
TRUNCATE TABLE prosp_workflow;
ALTER TABLE prosp_workflow CHANGE id_root id_root INT( 11 ) NOT NULL;
TRUNCATE TABLE user;
TRUNCATE TABLE prosp_repository;